name: 'arc_analytics'
version: '1.0.0'
config-version: 2

profile: 'arc_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  arc_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  # Add any project variables here
  salesforce_schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
  database: "{{ env_var('SNOWFLAKE_DATABASE') }}"

seeds:
  whizzy_warehouse:
    +schema: staging
    +materialized: table

tests:
  +store_failures: true
  +severity: warn
