-- Custom analysis - generated by ARC
{{
  config(
    materialized='table',
    description='Custom analysis - generated by ARC'
  )
}}

select
  count(*) as total_opportunities,
  sum(amount) as total_amount,
  avg(amount) as avg_amount
from {{ ref('fct_opportunity') }}
where close_date >= dateadd('month', -6, current_date())
limit 200