-- Win rate trend analysis - generated by ARC
{{
  config(
    materialized='table',
    description='Win rate trend analysis by industry and owner'
  )
}}

WITH opportunity_data AS (
  SELECT 
    Id,
    Amount,
    CloseDate,
    IsClosed,
    IsWon,
    OwnerId,
    AccountId
  FROM {{ ref('fct_opportunity') }}
  WHERE CloseDate >= DATEADD('month', -18, CURRENT_DATE())
    AND IsClosed = true
),

account_data AS (
  SELECT 
    Id,
    Industry,
    Type as AccountType
  FROM {{ ref('dim_account') }}
),

owner_data AS (
  SELECT 
    Id,
    Name as OwnerName,
    Team__c as Team
  FROM {{ ref('dim_owner') }}
),

quarterly_win_rates AS (
  SELECT 
    DATE_TRUNC('quarter', CloseDate) as Quarter,
    COALESCE(a.Industry, 'Unknown') as Industry,
    COALESCE(o.OwnerName, 'Unknown') as OwnerName,
    COALESCE(o.Team, 'Unknown') as Team,
    COUNT(*) as TotalOpportunities,
    SUM(CASE WHEN IsWon = true THEN 1 ELSE 0 END) as WonOpportunities,
    SUM(CASE WHEN IsWon = true THEN Amount ELSE 0 END) as WonAmount,
    SUM(Amount) as TotalAmount
  FROM opportunity_data opp
  LEFT JOIN account_data a ON opp.AccountId = a.Id
  LEFT JOIN owner_data o ON opp.OwnerId = o.Id
  GROUP BY 1, 2, 3, 4
)

SELECT 
  Quarter,
  Industry,
  OwnerName,
  Team,
  TotalOpportunities,
  WonOpportunities,
  WonAmount,
  TotalAmount,
  CASE 
    WHEN TotalOpportunities > 0 
    THEN ROUND(WonOpportunities * 100.0 / TotalOpportunities, 2)
    ELSE 0 
  END as WinRate,
  CASE 
    WHEN TotalAmount > 0 
    THEN ROUND(WonAmount * 100.0 / TotalAmount, 2)
    ELSE 0 
  END as RevenueWinRate,
  LAG(WonOpportunities) OVER (PARTITION BY Industry, OwnerName ORDER BY Quarter) as PrevQuarterWon,
  CASE 
    WHEN LAG(WonOpportunities) OVER (PARTITION BY Industry, OwnerName ORDER BY Quarter) > 0
    THEN ROUND((WonOpportunities - LAG(WonOpportunities) OVER (PARTITION BY Industry, OwnerName ORDER BY Quarter)) * 100.0 / 
               LAG(WonOpportunities) OVER (PARTITION BY Industry, OwnerName ORDER BY Quarter), 2)
    ELSE 0 
  END as QoQWinRateChange
FROM quarterly_win_rates
ORDER BY Quarter DESC, Industry, OwnerName
