-- Win rate analysis by industry - generated by ARC
{{
  config(
    materialized='table',
    description='Win rate analysis by industry - generated by ARC'
  )
}}

with f as (
  select * from {{ ref('fct_opportunity') }}
),
a as (
  select account_id, industry from {{ ref('dim_account') }}
)
select
  date_trunc('quarter', f.close_date) as close_quarter,
  coalesce(a.industry, 'Unknown') as industry,
  count(*) as opps,
  sum(case when f.is_won then 1 else 0 end) as wins,
  sum(case when f.is_won then f.amount else 0 end) as revenue_won,
  nullif(sum(case when f.is_won then 1 else 0 end), 0) / nullif(count(*), 0) as win_rate
from f 
left join a using (account_id)
where f.close_date >= dateadd('month', -18, current_date())
group by 1, 2
order by 1 desc, 3 desc
limit 200