-- Win rate analysis by owner - generated by ARC
{{
  config(
    materialized='table',
    description='Win rate analysis by owner - generated by ARC'
  )
}}

with f as (
  select * from {{ ref('fct_opportunity') }}
),
o as (
  select owner_id, owner_name from {{ ref('dim_owner') }}
)
select
  date_trunc('quarter', f.close_date) as close_quarter,
  coalesce(o.owner_name, 'Unknown') as owner_name,
  count(*) as opps,
  sum(case when f.is_won then 1 else 0 end) as wins,
  sum(case when f.is_won then f.amount else 0 end) as revenue_won,
  nullif(sum(case when f.is_won then 1 else 0 end), 0) / nullif(count(*), 0) as win_rate
from f 
left join o using (owner_id)
where f.close_date >= dateadd('month', -18, current_date())
group by 1, 2
order by 1 desc, 3 desc
limit 200